# Tuning Neural Networks with Normalization - Lab

## Introduction

For this lab on initialization and optimization, you'll build a neural network to perform a regression task.

It is worth noting that getting regression to work with neural networks can be difficult because the output is unbounded ($\hat y$ can technically range from $-\infty$ to $+\infty$, and the models are especially prone to exploding gradients. This issue makes a regression exercise the perfect learning case for tinkering with normalization and optimization strategies to ensure proper convergence!

## Objectives
You will be able to:
* Build a neural network using Keras
* Normalize your data to assist algorithm convergence
* Implement and observe the impact of various initialization techniques

In [1]:
import numpy as np
import pandas as pd
from keras.models import Sequential
from keras import initializers
from keras import layers
from keras.wrappers.scikit_learn import KerasRegressor
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn import preprocessing
from keras import optimizers
from sklearn.model_selection import train_test_split

Using TensorFlow backend.

## Loading the data

The data we'll be working with is data related to facebook posts published during the year of 2014 on the facebook page of a renowned cosmetics brand.  It includes 7 features known prior to post publication, and 12 features for evaluating the post impact. What we want to do is make a predictor for the number of "likes" for a post, taking into account the 7 features prior to posting.

First, let's import the data set and delete any rows with missing data. Afterwards, briefly preview the data.

In [21]:
#Your code here; load the dataset and drop rows with missing values. Then preview the data.
data = pd.read_csv('dataset_Facebook.csv', sep=';')
data.dropna(inplace=True)
data.columns

Index(['Page total likes', 'Type', 'Category', 'Post Month', 'Post Weekday',
       'Post Hour', 'Paid', 'Lifetime Post Total Reach',
       'Lifetime Post Total Impressions', 'Lifetime Engaged Users',
       'Lifetime Post Consumers', 'Lifetime Post Consumptions',
       'Lifetime Post Impressions by people who have liked your Page',
       'Lifetime Post reach by people who like your Page',
       'Lifetime People who have liked your Page and engaged with your post',
       'comment', 'like', 'share', 'Total Interactions'],
      dtype='object')

## Defining the Problem

Define X and Y and perform a train-validation-test split.

X will be:
* Page total likes
* Post Month
* Post Weekday
* Post Hour
* Paid
along with dummy variables for:
* Type
* Category

Y will be the `like` column.

In [53]:
#Your code here; define the problem.
# X = data.drop('like', axis=1)
# y = data['like']

# X = pd.get_dummies(X, columns=['Type', 'Category'])

data_clean = pd.get_dummies(data, columns=['Type', 'Category'])

# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=42)
# X_train, X_val, y_train, y_val = train_test_split(y_train, y_train, test_size=0.2, random_state=123)
# X_train.shape

train, validation = train_test_split(data_clean, test_size=0.2)

X_val = validation.iloc[:,0:18]
Y_val = validation.iloc[:,18]
X_train = train.iloc[:,0:18]
Y_train = train.iloc[:,18]
X_train

,Page total likes,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions,Type_Link
438,98195,3,6,6,0.0,5730,10083,103,71,97,8964,4830,92,2,32.0,15.0,49,1
244,130791,7,3,5,1.0,180480,319133,8072,4010,6242,108752,51456,3316,372,5172.0,790.0,6334,0
366,115368,4,2,13,0.0,6692,11859,905,742,1165,8391,4692,737,4,304.0,47.0,355,0
174,135195,9,7,3,0.0,4398,8105,584,446,669,4799,2616,431,5,204.0,34.0,243,0
79,137177,11,7,12,0.0,3754,8533,658,640,2085,6838,3224,598,2,29.0,7.0,38,0
69,137893,11,6,3,0.0,3102,5939,360,288,512,3537,1780,275,7,84.0,28.0,119,0
213,132201,8,4,11,1.0,1006,1594,277,268,354,1055,651,187,1,11.0,3.0,15,0
283,126141,6,7,4,1.0,9652,16968,1400,1381,2801,15917,8972,1035,1,34.0,4.0,39,0
412,106928,4,4,3,1.0,5290,8132,612,570,857,6032,3794,454,1,89.0,14.0,104,0
20,138414,12,1,3,0.0,2848,5066,200,142,184,3561,1963,157,3,66.0,12.0,81,0
87,137177,11,3,10,0.0,4012,7955,550,319,477,4625,2218,403,3,270.0,38.0,311,0
371,113028,4,6,3,1.0,17912,34774,2750,2567,6591,21009,11408,2256,17,447.0,123.0,587,0
1,139441,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164,0
401,107907,4,3,13,1.0,46192,80227,1364,1096,1697,32842,16960,762,9,329.0,38.0,376,0
494,85093,1,7,10,0.0,5400,9218,810,756,1003,5654,3230,422,10,125.0,41.0,176,0
454,93149,2,4,3,0.0,9528,16535,1383,1288,1834,11276,6260,630,14,198.0,70.0,282,0
387,109670,4,3,13,1.0,5402,8891,700,633,1078,6733,3992,514,0,112.0,14.0,126,0
238,131300,7,6,2,0.0,3384,6166,451,395,561,4708,2508,344,2,101.0,25.0,128,0
441,98195,3,5,4,1.0,1845,2670,9,9,9,1614,1008,9,0,0.0,0.0,0,0
301,124940,6,6,2,1.0,2823,4955,552,503,622,3579,1966,348,1,72.0,16.0,89,0
375,111620,4,4,7,1.0,12824,18929,830,623,864,15678,10968,705,0,286.0,30.0,316,0
208,132201,8,7,3,0.0,2594,4220,347,315,529,3418,2067,248,1,54.0,11.0,66,0
248,129600,7,1,6,0.0,3406,5656,571,512,731,4446,2598,355,1,98.0,19.0,118,0
367,115368,4,2,2,1.0,5594,9586,739,670,1048,5732,3256,555,12,138.0,39.0,189,0
323,123047,6,1,10,0.0,56672,104966,2579,1334,1850,78678,37408,1831,20,1372.0,47.0,1439,0
60,138185,11,3,11,1.0,10940,27951,417,335,591,15066,5100,319,8,101.0,14.0,123,0
184,134879,9,2,3,0.0,2363,4223,393,348,476,3332,1788,297,11,68.0,11.0,90,0
456,92935,2,3,9,1.0,3796,6737,949,940,1192,5249,2694,398,1,22.0,6.0,29,0
126,136393,10,7,3,0.0,3366,6647,474,345,495,3180,1674,385,3,198.0,41.0,242,0
458,92721,2,2,13,0.0,7228,12627,1239,1189,1612,9781,5348,606,5,128.0,32.0,165,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
350,116435,5,5,9,0.0,5728,10164,676,587,1049,6890,3714,475,3,155.0,32.0,190,0
296,125612,6,1,14,0.0,4248,7004,724,671,920,5063,3114,501,5,93.0,19.0,117,0
348,117764,5,6,8,1.0,4336,7705,574,484,847,5156,2752,403,12,155.0,23.0,190,0
53,138329,11,7,3,0.0,2935,5439,237,182,401,3901,2044,201,4,64.0,19.0,87,0
265,128032,7,6,13,1.0,2628,4264,528,503,652,3086,1846,328,3,42.0,10.0,55,0
35,138895,12,1,11,0.0,4512,7808,423,284,431,5183,2954,316,6,172.0,21.0,199,0
427,100732,3,7,17,0.0,10844,22468,1409,1339,11064,18310,8848,1086,4,213.0,13.0,230,0
167,135428,9,4,2,1.0,10748,19724,892,498,719,13674,7624,704,8,485.0,64.0,557,0
11,139441,12,5,10,0.0,3112,5590,208,127,145,3887,2174,165,0,88.0,18.0,106,0
66,138185,11,7,11,0.0,2149,4120,197,156,219,3302,1640,161,0,48.0,7.0,55,0
73,137893,11,4,2,1.0,11444,46054,555,418,717,13737,4320,438,14,172.0,47.0,233,0
251,129600,7,6,11,0.0,26944,43464,877,740,1097,20270,10208,563,6,194.0,34.0,234,0
327,120050,5,5,9,1.0,3776,6736,577,529,719,4846,2614,371,3,97.0,22.0,122,0
212,132201,8,5,1,0.0,1659,2845,345,321,424,1604,915,239,3,36.0,11.0,50,0
354,116435,5,2,14,0.0,4132,7165,552,495,713,4908,2754,398,2,98.0,18.0,118,0
383,109670,4,6,3,0.0,4986,8198,662,614,788,5685,3230,469,2,92.0,28.0,122,0
334,119198,5,1,2,0.0,10152,17099,1636,1599,2755,15382,8980,1613,2,55.0,10.0,67,0
419,102112,3,3,4,0.0,5080,8238,523,505,727,6630,3892,403,0,39.0,14.0,53,0
192,133679,8,1,4,0.0,2295,3721,377,324,402,3121,1882,269,0,63.0,7.0,70,0
295,125612,6,2,2,0.0,11620,21564,1160,1138,2042,20024,10568,920,5,54.0,7.0,66,0
288,126141,6,4,12,0.0,20896,29062,1418,1038,2048,19738,13656,998,103,469.0,33.0,605,0
308,124940,6,2,13,0.0,22464,29650,1029,934,1408,9376,6864,546,3,142.0,18.0,163,0
83,137177,11,5,10,1.0,2938,5799,321,243,379,3668,1848,236,2,101.0,19.0,122,0
461,92400,2,1,4,0.0,5880,10115,1291,1264,1878,8536,4884,706,5,79.0,11.0,95,0
130,136393,10,6,11,0.0,910,1673,207,201,247,1503,782,176,0,8.0,2.0,10,0
85,137177,11,4,9,1.0,2566,5244,384,280,469,3834,1806,266,10,140.0,8.0,158,0
393,109670,4,7,14,0.0,3884,6406,518,483,597,4747,2686,392,1,57.0,13.0,71,0
359,116091,5,7,2,0.0,6984,12066,780,631,1116,8188,4776,570,25,256.0,54.0,335,0
369,113028,4,7,3,1.0,5582,9903,708,620,923,6315,3422,557,2,163.0,35.0,200,0
272,127082,7,3,3,1.0,76096,94644,2889,2495,4596,31096,19744,1276,22,534.0,31.0,587,0

## Building a Baseline Model

Next, build a naive baseline model to compare performance against is a helpful reference point. From there, you can then observe the impact of various tunning procedures which will iteratively improve your model.

In [55]:
#Simply run this code block, later you'll modify this model to tune the performance
np.random.seed(123)
model = Sequential()
model.add(layers.Dense(8, input_dim=18, activation='relu'))
model.add(layers.Dense(1, activation = 'linear'))

model.compile(optimizer= "sgd" ,loss='mse',metrics=['mse'])
hist = model.fit(X_train, Y_train, batch_size=32, 
                 epochs=100, validation_data = (X_val, Y_val), verbose=0)

### Evaluating the Baseline

Evaluate the baseline model for the training and validation sets.

In [58]:
#Your code here; evaluate the model with MSE
from sklearn.metrics import mean_squared_error

preds_train = model.predict(X_train)
preds_test = model.predict(X_test)

ValueError: Error when checking input: expected dense_27_input to have shape (18,) but got array with shape (23,)

In [45]:
#Your code here; inspect the loss function through the history object
hist.history

{'val_loss': [nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan],
 'val_mean_squared_error': [nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan],
 'loss': [nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan],
 'mean_squared_error': [nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan]}

> Notice this extremely problematic behavior: all the values for training and validation loss are "nan". This indicates that the algorithm did not converge. The first solution to this is to normalize the input. From there, if convergence is not achieved, normalizing the output may also be required.

## Normalize the Input Data

Normalize the input features by subtracting each feature mean and dividing by the standard deviation in order to transform each into a standard normal distribution. Then recreate the train-validate-test sets with the transformed input data.

In [ ]:
## standardize/categorize

## Refit the Model and Reevaluate

Great! Now refit the model and once again assess it's performance on the training and validation sets.

In [ ]:
#Your code here; refit a model as shown above

In [ ]:
#Rexamine the loss function

> Note that you still haven't achieved convergence! From here, it's time to normalize the output data.

## Normalizing the output

Normalize Y as you did X by subtracting the mean and dividing by the standard deviation. Then, resplit the data into training and validation sets as we demonstrated above, and retrain a new model using your normalized X and Y data.

In [ ]:
#Your code here: redefine Y after normalizing the data.

In [ ]:
#Your code here; create training and validation sets as before. Use random seed 123.

In [ ]:
#Your code here; rebuild a simple model using a relu layer followed by a linear layer. (See our code snippet above!)

Again, reevaluate the updated model.

In [ ]:
#Your code here; MSE

In [ ]:
#Your code here; loss function

Great! Now that you have a converged model, you can also experiment with alternative optimizers and initialization strategies to see if you can find a better global minimum. (After all, the current models may have converged to a local minimum.)

## Using Weight Initializers

Below, take a look at the code provided to see how to modify the neural network to use alternative initialization and optimization strategies. At the end, you'll then be asked to select the model which you believe is the strongest.

##  He Initialization

In [19]:
np.random.seed(123)
model = Sequential()
model.add(layers.Dense(8, input_dim=12, kernel_initializer= "he_normal",
                activation='relu'))
model.add(layers.Dense(1, activation = 'linear'))

model.compile(optimizer= "sgd" ,loss='mse',metrics=['mse'])
hist = model.fit(X_train, Y_train, batch_size=32, 
                 epochs=100, validation_data = (X_val, Y_val),verbose=0)

In [20]:
pred_train = model.predict(X_train).reshape(-1)
pred_val = model.predict(X_val).reshape(-1)

MSE_train = np.mean((pred_train-Y_train)**2)
MSE_val = np.mean((pred_val-Y_val)**2)

In [21]:
print(MSE_train)
print(MSE_val)

1.0392949820359312
0.8658544030836142

## Lecun Initialization

In [22]:
np.random.seed(123)
model = Sequential()
model.add(layers.Dense(8, input_dim=12, 
                kernel_initializer= "lecun_normal", activation='tanh'))
model.add(layers.Dense(1, activation = 'linear'))

model.compile(optimizer= "sgd" ,loss='mse',metrics=['mse'])
hist = model.fit(X_train, Y_train, batch_size=32, 
                 epochs=100, validation_data = (X_val, Y_val), verbose=0)

In [23]:
pred_train = model.predict(X_train).reshape(-1)
pred_val = model.predict(X_val).reshape(-1)

MSE_train = np.mean((pred_train-Y_train)**2)
MSE_val = np.mean((pred_val-Y_val)**2)

In [24]:
print(MSE_train)
print(MSE_val)

1.0307351124941144
0.9292005788570431

Not much of a difference, but a useful note to consider when tuning your network. Next, let's investigate the impact of various optimization algorithms.

## RMSprop

In [25]:
np.random.seed(123)
model = Sequential()
model.add(layers.Dense(8, input_dim=12, activation='relu'))
model.add(layers.Dense(1, activation = 'linear'))

model.compile(optimizer= "rmsprop" ,loss='mse',metrics=['mse'])
hist = model.fit(X_train, Y_train, batch_size=32, 
                 epochs=100, validation_data = (X_val, Y_val), verbose = 0)

In [26]:
pred_train = model.predict(X_train).reshape(-1)
pred_val = model.predict(X_val).reshape(-1)

MSE_train = np.mean((pred_train-Y_train)**2)
MSE_val = np.mean((pred_val-Y_val)**2)

In [27]:
print(MSE_train)
print(MSE_val)

1.020200641136699
0.9421919606123765

## Adam

In [28]:
np.random.seed(123)
model = Sequential()
model.add(layers.Dense(8, input_dim=12, activation='relu'))
model.add(layers.Dense(1, activation = 'linear'))

model.compile(optimizer= "Adam" ,loss='mse',metrics=['mse'])
hist = model.fit(X_train, Y_train, batch_size=32, 
                 epochs=100, validation_data = (X_val, Y_val), verbose = 0)

In [29]:
pred_train = model.predict(X_train).reshape(-1)
pred_val = model.predict(X_val).reshape(-1)

MSE_train = np.mean((pred_train-Y_train)**2)
MSE_val = np.mean((pred_val-Y_val)**2)

In [30]:
print(MSE_train)
print(MSE_val)

1.0219766410555322
0.9477664629838952

## Learning Rate Decay with Momentum

In [31]:
np.random.seed(123)
sgd = optimizers.SGD(lr=0.03, decay=0.0001, momentum=0.9)
model = Sequential()
model.add(layers.Dense(8, input_dim=12, activation='relu'))
model.add(layers.Dense(1, activation = 'linear'))

model.compile(optimizer= sgd ,loss='mse',metrics=['mse'])
hist = model.fit(X_train, Y_train, batch_size=32, 
                 epochs=100, validation_data = (X_val, Y_val), verbose = 0)

In [32]:
pred_train = model.predict(X_train).reshape(-1)
pred_val = model.predict(X_val).reshape(-1)

MSE_train = np.mean((pred_train-Y_train)**2)
MSE_val = np.mean((pred_val-Y_val)**2)

In [33]:
print(MSE_train)
print(MSE_val)

0.8667952792265361
1.1040802536956849

## Selecting a Final Model

Now, select the model with the best performance based on the training and validation sets. Evaluate this top model using the test set!

In [ ]:
#Your code here

## Summary  

In this lab, you worked to ensure your model converged properly. Additionally, you also investigated the impact of varying initialization and optimization routines.